import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import useRobotStore from '../../store/useRobotStore';

// Import the mesh components generated by gltf-jsx
import { Model as BaseLink } from './meshes/BaseLink';
import { Model as Link1 } from './meshes/Link1';
import { Model as Link2 } from './meshes/Link2';
import { Model as Link3 } from './meshes/Link3';
import { Model as Link4 } from './meshes/Link4';
import { Model as Link5 } from './meshes/Link5';
import { Model as Link6 } from './meshes/Link6';

const jointColors = ['#2d74c8', '#3c9b68', '#e0a32f', '#d25353', '#7c62c9', '#2698a8'];

const JointHandle = ({ index, angle, selected, onSelect, onChange }) => {
  const drag = useRef(null);

  if (!onChange) return null;

  const pointerX = (event) => event.nativeEvent?.clientX ?? event.clientX ?? 0;

  return (
    <mesh
      onPointerDown={(event) => {
        event.stopPropagation();
        event.target.setPointerCapture(event.pointerId);
        drag.current = { x: pointerX(event), angle };
        onSelect(index);
      }}
      onPointerMove={(event) => {
        if (!drag.current) return;
        event.stopPropagation();
        onChange(index, drag.current.angle + (pointerX(event) - drag.current.x) * 0.45);
      }}
      onPointerUp={(event) => {
        event.stopPropagation();
        event.target.releasePointerCapture(event.pointerId);
        drag.current = null;
      }}
      onPointerCancel={() => {
        drag.current = null;
      }}
    >
      <torusGeometry args={[selected ? 0.043 : 0.038, 0.0045, 10, 40]} />
      <meshBasicMaterial
        color={jointColors[index]}
        transparent
        opacity={selected ? 1 : 0.62}
        depthTest={false}
      />
    </mesh>
  );
};

const RobotModel = ({
  displayThetas,
  interactive = false,
  selectedJoint = 0,
  onJointSelect,
  onJointChange,
  endEffectorRef,
}) => {
  const statusThetas = useRobotStore((state) => state.status.thetas);
  const thetas = displayThetas ?? statusThetas;

  const joint1Ref = useRef();
  const joint2Ref = useRef();
  const joint3Ref = useRef();
  const joint4Ref = useRef();
  const joint5Ref = useRef();
  const joint6Ref = useRef();

  useFrame(() => {
    if (thetas && thetas.length === 6) {
      const degToRad = Math.PI / 180;

      // The joint's <axis> is "0 0 1", so we rotate around the Z-axis of the joint's group.
      if (joint1Ref.current)
        joint1Ref.current.rotation.z = thetas[0] * degToRad;
      if (joint2Ref.current)
        joint2Ref.current.rotation.z = thetas[1] * degToRad;
      if (joint3Ref.current)
        joint3Ref.current.rotation.z = thetas[2] * degToRad;
      if (joint4Ref.current)
        joint4Ref.current.rotation.z = thetas[3] * degToRad;
      if (joint5Ref.current)
        joint5Ref.current.rotation.z = thetas[4] * degToRad;
      if (joint6Ref.current)
        joint6Ref.current.rotation.z = thetas[5] * degToRad;
    }
  });

  return (
    // Base rotation to stand the model up (Z-up URDF to Y-up Three.js)
    <group rotation={[-Math.PI / 2, 0, 0]}>
      {/* Base Link - This is the root */}
      {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
      <BaseLink position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

      {/* Joint 1: Connects base_link to Link1 */}
      {/* URDF <joint><origin xyz="0 0 0.181" rpy="0 0 0" /> */}
      <group position={[0, 0, 0.181]} rotation={[0, 0, 0]} ref={joint1Ref}>
        {interactive && (
          <JointHandle
            index={0}
            angle={thetas[0]}
            selected={selectedJoint === 0}
            onSelect={onJointSelect}
            onChange={onJointChange}
          />
        )}
        {/* Visual for Link1 */}
        {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
        <Link1 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

        {/* Joint 2: Connects Link1 to Link2 */}
        {/* URDF <joint><origin xyz="0 0 0" rpy="1.5708 1.5708 0" /> */}
        <group
          position={[0, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          ref={joint2Ref}
        >
          {interactive && (
            <JointHandle
              index={1}
              angle={thetas[1]}
              selected={selectedJoint === 1}
              onSelect={onJointSelect}
              onChange={onJointChange}
            />
          )}
          {/* Visual for Link2 */}
          {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
          <Link2 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

          {/* Joint 3: Connects Link2 to Link3 */}
          {/* URDF <joint><origin xyz="-0.203 0 0" rpy="0 0 -1.5708" /> */}
          <group position={[-0.203, 0, 0]} rotation={[0, 0, 0]} ref={joint3Ref}>
            {interactive && (
              <JointHandle
                index={2}
                angle={thetas[2]}
                selected={selectedJoint === 2}
                onSelect={onJointSelect}
                onChange={onJointChange}
              />
            )}
            {/* Visual for Link3 */}
            {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
            <Link3 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

            {/* Joint 4: Connects Link3 to Link4 */}
            {/* URDF <joint><origin xyz="-0.188 0 0" rpy="0 0 0" /> */}
            <group
              position={[-0.188, 0, 0]}
              rotation={[0, 0, 0]}
              ref={joint4Ref}
            >
              {interactive && (
                <JointHandle
                  index={3}
                  angle={thetas[3]}
                  selected={selectedJoint === 3}
                  onSelect={onJointSelect}
                  onChange={onJointChange}
                />
              )}
              {/* Visual for Link4 */}
              {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
              <Link4 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

              {/* Joint 5: Connects Link4 to Link5 */}
              {/* URDF <joint><origin xyz="0 0 0.073" rpy="1.5708 0 0" /> */}
              <group
                position={[0, 0, 0.073]}
                rotation={[Math.PI / 2, 0, 0]}
                ref={joint5Ref}
              >
                {interactive && (
                  <JointHandle
                    index={4}
                    angle={thetas[4]}
                    selected={selectedJoint === 4}
                    onSelect={onJointSelect}
                    onChange={onJointChange}
                  />
                )}
                {/* Visual for Link5 */}
                {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
                <Link5
                  position={[0, 0, 0]}
                  rotation={[0, -Math.PI / 2, -Math.PI / 2]}
                />

                {/* Joint 6: Connects Link5 to Link6 */}
                {/* URDF <joint><origin xyz="0 0 0.06825" rpy="1.5708 0 1.5708" /> */}
                <group
                  position={[0, 0, 0.06825]}
                  rotation={[-Math.PI / 2, 0, 0.0]}
                  ref={joint6Ref}
                >
                  {interactive && (
                    <JointHandle
                      index={5}
                      angle={thetas[5]}
                      selected={selectedJoint === 5}
                      onSelect={onJointSelect}
                      onChange={onJointChange}
                    />
                  )}
                  {/* Visual for Link6 */}
                  {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
                  <Link6 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                  <group ref={endEffectorRef} position={[0, 0, 0.045]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default RobotModel;
