import React, { useRef, useMemo } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import useRobotStore from '../../store/useRobotStore';

// Import the mesh components generated by gltf-jsx
import { Model as BaseLink } from './meshes/BaseLink';
import { Model as Link1 } from './meshes/Link1';
import { Model as Link2 } from './meshes/Link2';
import { Model as Link3 } from './meshes/Link3';
import { Model as Link4 } from './meshes/Link4';
import { Model as Link5 } from './meshes/Link5';
import { Model as Link6 } from './meshes/Link6';

// --- HELPER FUNCTION: This is the key to the fix ---
// It correctly converts URDF <origin> tags to a Three.js Matrix4
function createTransformMatrix({ xyz, rpy }) {
  const position = new THREE.Vector3(...xyz);
  // URDF RPY is extrinsic XYZ, which corresponds to Three.js's 'XYZ' Euler order.
  const rotation = new THREE.Euler(...rpy, 'XYZ');

  const matrix = new THREE.Matrix4();
  matrix.compose(
    position,
    new THREE.Quaternion().setFromEuler(rotation),
    new THREE.Vector3(1, 1, 1)
  );
  return matrix;
}

// Reusable component for a joint
const Joint = ({ origin, jointRef, children }) => {
  // useMemo ensures the matrix is calculated only once
  const matrix = useMemo(() => createTransformMatrix(origin), [origin]);

  return (
    <group matrix={matrix} matrixAutoUpdate={false}>
      <group ref={jointRef}>{children}</group>
    </group>
  );
};

const RobotModel = () => {
  const thetas = useRobotStore((state) => state.status.thetas);

  const joint1Ref = useRef();
  const joint2Ref = useRef();
  const joint3Ref = useRef();
  const joint4Ref = useRef();
  const joint5Ref = useRef();
  const joint6Ref = useRef();

  useFrame(() => {
    if (thetas && thetas.length === 6) {
      const degToRad = Math.PI / 180;

      // The joint's <axis> is "0 0 1", so we rotate around the Z-axis of the joint's group.
      if (joint1Ref.current)
        joint1Ref.current.rotation.z = thetas[0] * degToRad;
      if (joint2Ref.current)
        joint2Ref.current.rotation.z = thetas[1] * degToRad;
      if (joint3Ref.current)
        joint3Ref.current.rotation.z = thetas[2] * degToRad;
      if (joint4Ref.current)
        joint4Ref.current.rotation.z = thetas[3] * degToRad;
      if (joint5Ref.current)
        joint5Ref.current.rotation.z = thetas[4] * degToRad;
      if (joint6Ref.current)
        joint6Ref.current.rotation.z = thetas[5] * degToRad;
    }
  });

  return (
    // Base rotation to stand the model up (Z-up URDF to Y-up Three.js)
    <group rotation={[-Math.PI / 2, 0, 0]}>
      {/* Base Link - This is the root */}
      {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
      <BaseLink position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

      {/* Joint 1: Connects base_link to Link1 */}
      {/* URDF <joint><origin xyz="0 0 0.181" rpy="0 0 0" /> */}
      <group position={[0, 0, 0.181]} rotation={[0, 0, 0]} ref={joint1Ref}>
        {/* Visual for Link1 */}
        {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
        <Link1 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

        {/* Joint 2: Connects Link1 to Link2 */}
        {/* URDF <joint><origin xyz="0 0 0" rpy="1.5708 1.5708 0" /> */}
        <group
          position={[0, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          ref={joint2Ref}
        >
          {/* Visual for Link2 */}
          {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
          <Link2 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

          {/* Joint 3: Connects Link2 to Link3 */}
          {/* URDF <joint><origin xyz="-0.203 0 0" rpy="0 0 -1.5708" /> */}
          <group position={[-0.203, 0, 0]} rotation={[0, 0, 0]} ref={joint3Ref}>
            {/* Visual for Link3 */}
            {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
            <Link3 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

            {/* Joint 4: Connects Link3 to Link4 */}
            {/* URDF <joint><origin xyz="-0.188 0 0" rpy="0 0 0" /> */}
            <group
              position={[-0.188, 0, 0]}
              rotation={[0, 0, 0]}
              ref={joint4Ref}
            >
              {/* Visual for Link4 */}
              {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
              <Link4 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />

              {/* Joint 5: Connects Link4 to Link5 */}
              {/* URDF <joint><origin xyz="0 0 0.073" rpy="1.5708 0 0" /> */}
              <group
                position={[0, 0, 0.073]}
                rotation={[Math.PI / 2, 0, 0]}
                ref={joint5Ref}
              >
                {/* Visual for Link5 */}
                {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
                <Link5
                  position={[0, 0, 0]}
                  rotation={[0, -Math.PI / 2, -Math.PI / 2]}
                />

                {/* Joint 6: Connects Link5 to Link6 */}
                {/* URDF <joint><origin xyz="0 0 0.06825" rpy="1.5708 0 1.5708" /> */}
                <group
                  position={[0, 0, 0.06825]}
                  rotation={[-Math.PI / 2, 0, 0.0]}
                  ref={joint6Ref}
                >
                  {/* Visual for Link6 */}
                  {/* URDF <visual><origin xyz="0 0 0" rpy="0 0 0" /> */}
                  <Link6 position={[0, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default RobotModel;
