/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 base_link.glb --output ../../../../src/components/three/meshes/BaseLink.jsx --root ../../.. 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { publicUrl } from '../../../publicUrl'

const modelUrl = publicUrl('urdf/ROBOARM.STEP.SLDASM/meshes/base_link.glb')

export function Model(props) {
  const { nodes } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.base_link.geometry} material={nodes.base_link.material} />
    </group>
  )
}

useGLTF.preload(modelUrl)
