/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Link6.glb --output ../../../../src/components/three/meshes/Link6.jsx --root ../../.. 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { publicUrl } from '../../../publicUrl'

const modelUrl = publicUrl('urdf/ROBOARM.STEP.SLDASM/meshes/Link6.glb')

export function Model(props) {
  const { nodes } = useGLTF(modelUrl)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Link6.geometry} material={nodes.Link6.material} />
    </group>
  )
}

useGLTF.preload(modelUrl)
