"""
Python bindings for dynamo_
"""

from __future__ import annotations

import collections.abc
import typing

__all__: list[str] = [
  "ArmCtrl",
  "InstanceStreamer",
  "Kinematics",
  "Orientation",
  "PumpCtrl",
  "RotCtrl",
  "Solutions",
  "Thetas",
  "init_logging",
]

class ArmCtrl:
  def __enter__(self) -> ArmCtrl: ...
  def __exit__(self, *args) -> None: ...
  def __init__(
    self,
    path: str = "/dev/ttyAMA2",
    sleep_time_interval: typing.SupportsInt | typing.SupportsIndex = 8000,
    debug: bool = False,
    enable_port: bool = True,
  ) -> None: ...
  def close_port(self) -> None: ...
  def forward(
    self,
    input_thetas: Thetas,
    velocity: typing.SupportsInt | typing.SupportsIndex = 5,
    verbose: bool = False,
  ) -> None: ...
  def is_open(self) -> bool: ...
  def open(self) -> None: ...
  def run_loop(self) -> None: ...
  def send(self, arg0: str) -> None: ...
  @property
  def device_path(self) -> str: ...

class InstanceStreamer:
  def __init__(
    self,
    kinematics: Kinematics,
    armctrl: ArmCtrl,
    rotctrl: RotCtrl,
    pumpctrl: PumpCtrl,
    init_thetas: Thetas,
    init_theta: typing.SupportsFloat | typing.SupportsIndex,
    verbose: bool,
    debug: bool,
  ) -> None: ...
  def ctrl_pump(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
  def ctrl_rot(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
  def ctrl_rot_fallback(
    self, arg0: typing.SupportsInt | typing.SupportsIndex
  ) -> None: ...
  def dual_derive(
    self,
    input_orientation: list = [],
    input_thetas: list = [],
    u_duration: typing.SupportsInt | typing.SupportsIndex = 3600000,
    return_states: bool = False,
  ) -> tuple[typing.Any, typing.Any, typing.Any]: ...
  def forward_kinematics(self, thetas: list) -> list: ...
  def get_direction_vector(self) -> list: ...
  def get_invert_axes(self) -> list: ...
  def get_roboarm_orientation(self) -> list: ...
  def get_roboarm_thetas(self) -> list: ...
  def get_states(
    self, input_thetas: list = [], verbose: bool = False
  ) -> typing.Any: ...
  def inverse_kinematics(self, orientation: list) -> list: ...
  def restore(self) -> None: ...
  def singular_derive(
    self, angle: typing.SupportsFloat | typing.SupportsIndex = 0.0
  ) -> None: ...
  @property
  def get_rotplat_theta(self) -> float: ...

class Kinematics:
  def __init__(self, enable_cache: bool = False) -> None: ...
  def get_cached_orientations(self) -> list: ...
  def get_states(self, input_thetas: Thetas, verbose: bool = False) -> typing.Any: ...
  def solve_forward_kinematics(
    self, input_thetas: Thetas, verbose: bool = False
  ) -> Orientation: ...
  def solve_inverse_kinematics(
    self, input_orientation: Orientation, last_thetas: Thetas, verbose: bool = False
  ) -> Solutions: ...

class Orientation:
  has_rot_mat: bool
  @typing.overload
  def __init__(self) -> None: ...
  @typing.overload
  def __init__(
    self,
    x: typing.SupportsFloat | typing.SupportsIndex,
    y: typing.SupportsFloat | typing.SupportsIndex,
    z: typing.SupportsFloat | typing.SupportsIndex,
    a: typing.SupportsFloat | typing.SupportsIndex,
    b: typing.SupportsFloat | typing.SupportsIndex,
    c: typing.SupportsFloat | typing.SupportsIndex,
  ) -> None: ...
  @property
  def RotMat(self) -> list: ...
  @RotMat.setter
  def RotMat(self, arg1: collections.abc.Sequence) -> None: ...
  @property
  def a(self) -> float: ...
  @a.setter
  def a(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
  @property
  def b(self) -> float: ...
  @b.setter
  def b(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
  @property
  def c(self) -> float: ...
  @c.setter
  def c(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
  @property
  def x(self) -> float: ...
  @x.setter
  def x(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
  @property
  def y(self) -> float: ...
  @y.setter
  def y(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
  @property
  def z(self) -> float: ...
  @z.setter
  def z(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class PumpCtrl:
  def __init__(self, path: str, debug: bool, enable_port: bool = True) -> None: ...

class RotCtrl:
  def __enter__(self) -> RotCtrl: ...
  def __exit__(self, *args) -> None: ...
  def __init__(
    self,
    x: typing.SupportsFloat | typing.SupportsIndex = 0.24,
    y: typing.SupportsFloat | typing.SupportsIndex = 0.0,
    z: typing.SupportsFloat | typing.SupportsIndex = 0.24,
    theta: typing.SupportsFloat | typing.SupportsIndex = 0.0,
    path: str = "/dev/ttyAMA2",
    debug: bool = False,
    enable_port: bool = True,
  ) -> None: ...
  def close_port(self) -> None: ...
  def forward(
    self, rot_angle: typing.SupportsFloat | typing.SupportsIndex, verbose: bool = False
  ) -> None: ...
  def is_open(self) -> bool: ...
  def open(self) -> None: ...
  def send(self, arg0: str) -> None: ...
  @property
  def device_path(self) -> str: ...

class Solutions:
  def __init__(self) -> None: ...
  @property
  def solution_flags(self) -> list: ...
  @solution_flags.setter
  def solution_flags(self, arg1: collections.abc.Sequence) -> None: ...
  @property
  def solutions(self) -> list: ...
  @solutions.setter
  def solutions(self, arg1: collections.abc.Sequence) -> None: ...

class Thetas:
  def __add__(self, arg0: Thetas) -> Thetas: ...
  @typing.overload
  def __init__(self) -> None: ...
  @typing.overload
  def __init__(
    self,
    arg0: typing.SupportsFloat | typing.SupportsIndex,
    arg1: typing.SupportsFloat | typing.SupportsIndex,
    arg2: typing.SupportsFloat | typing.SupportsIndex,
    arg3: typing.SupportsFloat | typing.SupportsIndex,
    arg4: typing.SupportsFloat | typing.SupportsIndex,
    arg5: typing.SupportsFloat | typing.SupportsIndex,
  ) -> None: ...
  def __sub__(self, arg0: Thetas) -> Thetas: ...
  @property
  def thetas(self) -> list: ...
  @thetas.setter
  def thetas(self, arg1: collections.abc.Sequence) -> None: ...

def init_logging(arg0: str) -> None:
  """
  Initialize files and sinks for dynamo_
  """
